### ISSUE TITLE
Install problem on Redmine 2.6.4

### ISSUE THREAD

**Issue by IDSUK** [jrupesh/event_notifications#14]
I have run default install and received the following error:
RAILS_ENV=production rake redmine:plugins:migrate NAME=event_notifications
rake aborted!
NameError: uninitialized constant PrincipalMembershipsController
/opt/bitnami/apps/redmine/htdocs/plugins/event_notifications/lib/patches/principal_memberships_controller_patch.rb:18:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/event_notifications/init.rb:14:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:150:in `block in load'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in `load'
/opt/bitnami/apps/redmine/htdocs/config/initializers/30-redmine.rb:19:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by IDSUK** [comment]
Sourced a copy of file principal_memberships_controller.rb from here:
https://github.com/redmine/redmine/blob/master/app/controllers/principal_memberships_controller.rb
now looks like a clean install of event notifier. This has brought the site back but now have 500 Internal error when clicking to configure plugin.
Production log:
  Rendered plugins/event_notifications/app/views/settings/_event_notifications_settings.html.erb (2.4ms)
  Rendered settings/plugin.html.erb within layouts/admin (3.1ms)
Completed 500 Internal Server Error in 5.2ms

ActionView::Template::Error (undefined method `order' for #<Array:0x007f6eb82f8f18>):
    32: 
    33: 
    34: 	<h4><%= l(:enable_notification_for_project_issue_categories)%></h4>
    35: 	<% Project.all.order('lft ASC').each do |project|
    36: 		if project.issue_categories.any? %>
    37: 			<p>
    38: 			  <label><%= project.name %></label>
  app/views/settings/plugin.html.erb:6:in `block in _4ef5abfa4b77dcf783082018d5b0e0e1'
  app/views/settings/plugin.html.erb:4:in `_4ef5abfa4b77dcf783082018d5b0e0e1'
