### ISSUE TITLE
Problem with installing on redmine 3.3.1 with ruby 2.2.4p230

### ISSUE THREAD

**Issue by RafalPydyniak** [jrupesh/event_notifications#33]
Hi,
I wanted to install the plugin but I have some problems with it. I cloned the repo into /plugins directory, I stopped the redmine and then I tried to migrate the database but the following error has occured

/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
Support of Ruby version lower than 2.3 will be dropped in 2017
rake aborted!
LoadError: cannot load such file -- event_notification/patches/users_helper_patch
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/easy/easyredmine/plugins/event_notifications/init.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/easy/easyredmine/plugins/easyproject/init.rb:385:in `load_plugin_init'
/home/easy/easyredmine/plugins/easyproject/init.rb:371:in `block in load_all_plugins'
/home/easy/easyredmine/plugins/easyproject/init.rb:370:in `each'
/home/easy/easyredmine/plugins/easyproject/init.rb:370:in `load_all_plugins'
/home/easy/easyredmine/plugins/easyproject/init.rb:339:in `init!'
/home/easy/easyredmine/plugins/easyproject/init.rb:391:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/easy/easyredmine/config/initializers/22-change_plugins_order.rb:15:in `load'
/home/easy/easyredmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/home/easy/easyredmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/bin/ruby_executable_hooks:15:in `<main>'

Any ideas what did could go wrong and how to fix it?

**Comment by jrupesh** [comment]
Were you able to solve?
